language: java
jdk: openjdk8
os: osx


cache:
  directories:
  - $HOME/.m2
  - $HOME/.leelaz

install:
  - sh scripts/make-leelaz.sh
  - sh scripts/download-network.sh

script:
  - mvn test
  - mvn com.coveo:fmt-maven-plugin:check
